force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <description>Exam is used to store Exam related information.</description>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Questions object is used to store questions related information.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exam Name</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question field describes the question name</description>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestCommunityQuery.cls
@isTest
private class TestCommunityQuery {
    @isTest
    static void testCommunityUserQuery() {
        User communityUser = [
            SELECT Id FROM User WHERE Profile.Name = 'Quiz Profile' LIMIT 1
        ];

        System.runAs(communityUser) {
            List<Question__c> qs = [
                SELECT Id, Question__c, Exam_Name__r.Name
                FROM Question__c
                WHERE Exam_Name__r.Name = 'Salesforce CPQ'
            ];
            System.debug('Questions visible to community user: ' + qs.size());
        }
    }
}